### ISSUE TITLE
Urge to add topic:'hacktoberfest' to the repository

### ISSUE THREAD

**Issue by keivalya** [RishabhDevbanshi/Emojipedia#105]
An important update regarding HACKTOBERFEST:

```
PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)
```

From the link: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by RishabhDevbanshi** [comment]
> An important update regarding HACKTOBERFEST:
> 
> ```
> PRs count if:
> Submitted in a repo with the hacktoberfest topic AND
> during the month of October AND (
>   The PR is merged OR
>   The PR is labelled as hacktoberfest-accepted by a maintainer OR
>   The PR has been approved
> )
> ```
> 
> From the link: https://hacktoberfest.digitalocean.com/hacktoberfest-update

Done
