### ISSUE TITLE
Problem in hosting on Github pages.

### ISSUE THREAD

**Issue by RishabhDevbanshi** [RishabhDevbanshi/Emojipedia#79]
I want to host this project on github pages but I was facing some difficulty in doing so, everytime I am getting a 404. Could anyone help me with it please?

**Comment by Haqverdi** [comment]
i will help)

**Comment by RishabhDevbanshi** [comment]
It'll be a great help !

**Comment by Haqverdi** [comment]
https://github.com/RishabhDevbanshi/Emojipedia/pull/82

**Comment by KonradLinkowski** [comment]
Better use this deploy conf https://gist.github.com/KonradLinkowski/4b2b825d2540c4eecfc5dc1f9e42a87f and you will never need to deploy the site manually.
